### ISSUE TITLE
frontend not working after deployment of heroku 

### ISSUE THREAD

**Issue by chenjuexu** [XanderUZZZER/proShop#1]
hi,bro,I almost check your code with mine,every is the same.But after I deploy to heroku:
https://imperfectioncs.herokuapp.com/
Only backend works.Anything wrong?

**Comment by chenjuexu** [comment]
This is git's repository:https://github.com/chenjuexu/imperfectioncs

**Comment by XanderUZZZER** [comment]
> hi,bro,I almost check your code with mine,every is the same.But after I deploy to heroku: https://imperfectioncs.herokuapp.com/ Only backend works.Anything wrong?

1.
server.js
remove these lines (21, 22, 23). Your back instead giving index.html and all static files for UI, gives 'Api is running' string
![image](https://user-images.githubusercontent.com/20344432/136451869-c4f12347-fa6b-4c61-bdc1-33a1602b6d59.png)

2.
Heroku App Settings
Reveal env vars, and check them, especially NODE_ENV. If it is not assigned - set it to 'production'
![image](https://user-images.githubusercontent.com/20344432/136452553-426be754-bd96-4498-a6b1-303b768749e8.png)

3.
And try to check deploy/build/run logs in heroku. 
![image](https://user-images.githubusercontent.com/20344432/136450208-ca90ca72-5380-48ec-a467-a9af2eb3ed00.png)

**Comment by chenjuexu** [comment]
thanks,the first step kill all issues.Thanks bro,hope you will find a good job.

**Comment by XanderUZZZER** [comment]
> thanks,the first step kill all issues.Thanks bro,hope you will find a good job.

Wish you keep going and never give up

Viam supervadet vadens

**Comment by chenjuexu** [comment]
Thanks I will,hope you everything good
Joshy chen
